management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
spring:
  application:
    name: endurance
  session:
    timeout: 15d
  datasource:
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    username: dbmasteruser
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
    user: dbmasteruser
    driver-class-name: org.postgresql.Driver
