spring:
  # Application Identity
  application:
    name: endurance

  # Database Configuration
  datasource:
    url: jdbc:postgresql://ls-3cd9e093f05f5c4d801b58031197f04063b55800.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Database Migration Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: endurance
    url: ${spring.datasource.url}    # Reuse the same URL
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    bedrock:
      aws:
        region: us-east-1
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
    chat:
      client:
        enabled: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native

# Monitoring/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    default-timeout: 180s  # 3 minutes
    db:
      timeout: 60s  # 1 minute for database health
    diskspace:
      timeout: 30s
    redis:
      timeout: 30s
  endpoint:
    health:
      show-details: when-authorized
      show-components: always