spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbbmaster
    username: dbmaster

  liquibase:
    url: jdbc:postgresql://localhost:5432/dbmaster
    user: dbmaster
    default-schema-name: endurance