spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbbmaster
    username: dbmaster
    password: 
  
  liquibase:
    url: jdbc:postgresql://localhost:5432/dbmaster
    user: dbmaster
    password:
    default-schema: endurance
  
  data:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          type: trace
          default_schema: endurance
  