management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
spring:
  application:
    name: endurance
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 23vj34rk4tm4ei2rsb5kp1rpfb
            clientSecret: 1cbpgh7gsk5mht6e9p02o7k0ccgan9dl7blj9s827b3f5fk84ruq
            scope: openid
            redirectUri: https://global.thonbecker.solutions/login/oauth2/code/cognito
            clientName: personalUserpoolenduranceappclient16CD304B-t0XQSfOpCedM
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DZ8a8Cqaw
            userNameAttribute: email
  session:
    timeout: 15d
  datasource:
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    username: dbmasteruser
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
    user: dbmasteruser
    driver-class-name: org.postgresql.Driver
