spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dbmasteruser
    # Add password if needed
    # password: your_password_here
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: dbmasteruser
    # password: your_password_here
    # Ensure Liquibase can create tables in public schema first
    default-schema-name: public