spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    default-schema-name: endurance