management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
  health:
    redis:
      enabled: off
server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
spring:
  application:
    name: endurance
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 59rkgaedh8hodrkpsngqcit4a5
            clientSecret: 1i0kfk2lomefnu34a8jgq8bvn0ujmcu2ip8i6p13khlmt910p5v2
            scope: openid  # OAuth2 client scope
            redirectUri: https://endurance.thonbecker.solutions/login/oauth2/code/cognito
            clientName: endurance
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_YOKSRMwld
            userNameAttribute: cognito:username
  session:
    jdbc:
      flush-mode: on_save
      platform: postgresql
    timeout: 15d
  datasource:
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    username: dbmasteruser
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    url: jdbc:postgresql://ls-ddd197eea6bb83c573f9dcd85c7091233de947c1.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    password: .>M.Azs_^eHbY}78Fa*k$V(Akr<>=M5^
    user: dbmasteruser
    driver-class-name: org.postgresql.Driver
